repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.5.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-import-order
          - pep8-naming
          # The following is disabled due to a runtime error
          # - flake8-docstrings
          - mccabe
