dist: bionic

sudo: required

git:
  submodules: false

services:
  - docker

language: python

python:
  - 3.6

before_install:
  - export TRAVIS_BRANCH_SAFE=$(echo $TRAVIS_BRANCH | sed "s/[/]/-/")
  - sudo docker pull crccheck/hello-world
  - pip install codecov pytest-cov
  - sudo mkdir -p /tmp/coverage
  - sudo chmod a+w /tmp/coverage
  - sudo service postgresql stop
  - sudo service redis-server stop

install:
  - make -j2 build
  - docker-compose run --rm web python manage.py migrate
  - docker-compose up -d

script:
  - docker-compose run --rm -v /tmp/coverage:/tmp/coverage web bash -c "COVERAGE_FILE=/tmp/coverage/.coverage.non-transactions pytest --cov-report= --cov=. -n 2"
  - docker-compose run --rm -v /tmp/coverage:/tmp/coverage web bash -c "COVERAGE_FILE=/tmp/coverage/.coverage.transactions pytest --cov-report= --cov=. --transactions"

after_success:
  - coverage combine /tmp/coverage/
  - codecov

deploy:
  - provider: script
    script: bash -c "docker login -u grandchallenge -p "$DOCKER_PASSWORD" && make push"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|staging$
