trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: |
    pip install codecov pytest-cov
    mkdir -p /tmp/coverage
    chmod a+w /tmp/coverage
  displayName: 'Install requirements'

- script: make -j build
  displayName: 'Build the containers'

- script: |
    docker-compose run --rm web python manage.py migrate
    docker-compose up -d
  displayName: 'Migrate and run the database'
