version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    command: >-
      dockerize -wait tcp://db:3306 -timeout 120s bash -c "
      python manage.py collectstatic --noinput
      && mkdir -p /dbox/Dropbox/media/
      && python manage.py migrate
      && python manage.py check_permissions
      && python manage.py initcomicdemo
      && gunicorn -b 0.0.0.0 config.wsgi
      "
    restart: always

  http:
    build: ./dockerfiles/http
    environment:
      - SERVER_NAME=localhost
      - SENDFILE_STATUS=off
    command: >-
      bash -c "envsubst '$$SERVER_NAME $$SENDFILE_STATUS' < /tmp/nginx.conf.template > /etc/nginx/nginx.conf
      && openssl req -x509 -newkey rsa:4096 -keyout /etc/ssl/private/$$SERVER_NAME.key -out /etc/ssl/certs/$$SERVER_NAME.crt -days 365 -nodes -subj '/CN=$$SERVER_NAME'
      && nginx -g 'daemon off;'"
    restart: always

  memcached:
    image: memcached:1.4
    restart: always

  dropbox:
    image: janeczku/dropbox
    volumes:
      - /srv/public/Dropbox/:/dbox/Dropbox/
    restart: always

  rabbitmq:
    image: rabbitmq:3.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
