version: '2'

services:

  db:
    image: mariadb:10.1
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_DATABASE=comic
    restart: always

  web:
    extends:
      file: docker-compose.common.yml
      service: web
    links:
      - db:mysql
      - memcached
      - minio
    volumes:
      - static:/static/
      - media:/dbox/Dropbox/media/
      - ./app:/app/
      # The docker socket is only needed for testing
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - dev.env
    build:
      args:
        - PIPENV_DEV=--dev

  http:
    extends:
      file: docker-compose.common.yml
      service: http
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
      - minio
    volumes:
      - static:/srv/public/static/:ro
      - media:/dbox/Dropbox/media/:ro

  memcached:
    extends:
      file: docker-compose.common.yml
      service: memcached

  rabbitmq:
    extends:
      file: docker-compose.common.yml
      service: rabbitmq
    hostname: rabbit
    ports:
      - "8080:15672"

  celery_worker:
    extends:
      file: docker-compose.common.yml
      service: web
    command: >-
      bash -c "
      sleep 120
      && celery -A config worker -l info -c 2
      "
    links:
      - db:mysql
      - rabbitmq
      - web
    volumes_from:
      - web

  celery_worker_evaluation:
    extends:
      file: docker-compose.common.yml
      service: web
    command: >-
      bash -c "
      sleep 120
      && celery -A config worker -l info -Q evaluation -c 2
      "
    links:
      - db:mysql
      - rabbitmq
      - web
    volumes_from:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  celery_beat:
    extends:
      file: docker-compose.common.yml
      service: web
    command: >-
      bash -c "
      sleep 120
      && celery -A config beat --pidfile= -l info
      "
    links:
      - db:mysql
      - rabbitmq
      - web
    volumes_from:
      - web

  flower:
    image: crgwbr/docker-celery-flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "5555:5555"
    links:
      - rabbitmq
    restart: always

  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    command: server /data
    env_file:
      - dev.env

volumes:
  static:
  media:
  minio-data:
