[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py38']

[tool.curlylint.rules]
html_has_lang = 'en'
django_forms_rendering = true
image_alt = true
# TODO: Enable this, would otherwise be a big change
# indent = 4
meta_viewport = true
no_autofocus = true
tabindex_no_positive = true

[tool.poetry]
name = "grand-challenge.org"
version = "0.1.0"
description = "A platform for end-to-end development of machine learning solutions in biomedical imaging"
license = "Apache-2.0"
authors = ["James Meakin <code@jmsmkn.com>"]
readme = "README.rst"
homepage = "https://grand-challenge.org/"
repository = "https://github.com/comic/grand-challenge.org/"
documentation = "https://comic.github.io/grand-challenge.org/"
packages = [
    { include = "grandchallenge", from = "app" },
]

[tool.poetry.dependencies]
python = "^3.8"
"beautifulsoup4" = "*"
celery = {extras = ["redis", "sqs"], version = "^4.4.6"}
django = "<3.2"
django-countries = "*"
django-crispy-forms = "*"
djangorestframework = "*"
docker = "*"
"oauth2" = "*"
python-magic = "*"
pytz = "*"
gunicorn = "*"
uvicorn = {version = "*", extras = ["standard"]}
django-celery-email = "*"
"psycopg2" = "*"
"django-select2" = "*"
django-celery-results = "*"
django-summernote = "*"
bleach = "*"
jsonschema = "*"
tldextract = "*"
django-autocomplete-light = "*"
django-storages = "*"
boto3 = "*"
whitenoise = "*"
brotli = "*"
djangorestframework-guardian = "*"
django-extensions = "*"
django-simple-history = "*"
sentry-sdk = "*"
django-cors-headers = "*"
scikit-learn = "*"
pandas = "*"
django-celery-beat = "!=1.6.0"
django-guardian = "!=2.2.0"
django-markdownx = "*"
django-filter = "*"
ua-parser = "*"
djangorestframework-csv = "*"
prometheus_client = "*"
humanize = "*"
disposable-email-domains = "*"
django-machina = "*"
django-haystack = "*"
citeproc-py = "*"
django-ipware = "*"
pyswot = "*"
django-redis = "*"
django-allauth = "*"
easy_thumbnails = "*"
drf-spectacular = "^0.13.2"
jinja2 = "^2.11.3"
openpyxl = "^3.0.6"
requests = "^2.25.1"
django_rest_knox = "^4.1.0"
numpy = "*"
Pillow = "*"
panimg = "^0.1.0"
django-activity-stream = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest-django = "*"
pytest-cov = "*"
pytest-mock = "*"
factory-boy = "*"
django-debug-toolbar = "*"
sphinx-autobuild = "*"
sphinx = "*"
pyupgrade = "*"
pytest-xdist = "*"
sphinx-autodoc-typehints = "*"
werkzeug = {extras = ["watchdog"], version = "^1.0.1"}
sphinx-rtd-theme = "*"
sphinxcontrib-plantuml = "*"
pytest-randomly = "*"
sphinxcontrib-django = "^0.5.1"
