name: CI
on: [push, pull_request]
jobs:

  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1.1.1
      - uses: actions/checkout@v1
      - run: python -m pip install pre-commit
      - run: pre-commit install
      - run: pre-commit run --all-files
